from __future__ import annotations

from pathlib import Path
from typing import Annotated

import typer

from binding.app import app
from binding.services.label import run_label


@app.command()
def label(
    input_file: Annotated[
        Path,
        typer.Argument(
            exists=True,
            dir_okay=False,
            help="Binary .npy stack to label.",
        ),
    ],
    seeds: Annotated[
        Path,
        typer.Option(
            "--seeds",
            exists=True,
            dir_okay=False,
            help="Seed coordinate file (CSV/TXT/JSON/NPY) generated by spotiflow.",
        ),
    ],
) -> None:
    result = run_label(input_file, seeds=seeds)

    typer.echo(
        f"Saved {result.output_path} with shape={result.shape}, "
        f"dtype={result.dtype}, components={result.component_count}, "
        f"method=seeded-watershed, seed_file={result.seed_file}"
    )